# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-15 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
