# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-16 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_auto_20170515_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='score',
        ),
    ]
